### ISSUE TITLE
No se puede crear cuenta como desarrollador

### ISSUE THREAD

**Issue by yvogel** [oscarvalenzuelab/multidata-api-clients#10]
Hola, trato de crear una cuenta como desarrollador para pedir la key, pero me aparece el mensaje "Signup has been disabled" Ya no esta abierto para desarrolladores?

**Comment by oscarvalenzuelab** [comment]
Hola, te respondi por correo. Salu2

**Comment by fbritop** [comment]
Estimados,
La solicitud de API para obtener el KEY es de forma privada ahora?

**Comment by oscarvalenzuelab** [comment]
Envianos un correo. Saludos, Oscar
