### ISSUE TITLE
Siempre van a responder en xml, por que el request necesita ser en json?

### ISSUE THREAD

**Issue by oscarvalenzuelab** [oscarvalenzuelab/multidata-api-clients#2]
Andrés Peñailillo consultó:
Siempre van a responder en xml, por que el request necesita ser en json?

**Comment by oscarvalenzuelab** [comment]
No necesariamente debe ser XML, la respuesta puede estar en JSON, antes de este fin de semana crearemos un método adicional para solicitar la respuesta en JSON.

Me queda la duda de que tipo de solicitud estas realizando, puesto que ninguna de las apis requiere pasar datos en json, solo se pasan datos en la misma URL como REST.

**Comment by apenailillo** [comment]
Hola oscar, solo seguí tu ejemplo en [archivo php](https://github.com/oscarvalenzuelab/multidata-api-clients/blob/master/multidata.php#L9), supuse que era necesario definir eso

**Comment by oscarvalenzuelab** [comment]
Quizás fue muy confuso, lo cambiaré entonces muchas gracias!
En general, la petición puede no tener declarado un tipo, pero la respuesta la ofreceremos en JSON también.

**Comment by oscarvalenzuelab** [comment]
Hemos habilitado las respuestas JSON con nuevos métodos exclusivos para este fin. Enjoy!
