### ISSUE TITLE
XML de la respuesta no siempre tienen la misma estructura

### ISSUE THREAD

**Issue by oscarvalenzuelab** [oscarvalenzuelab/multidata-api-clients#3]
Andrés Peñailillo consultó:
me he dado cuenta que las respuestas no siempre tienen la misma estructura, a veces vienen los datos dentro de un nodo item y otras veces no, además que un nodo item puede tener cosas distintas y no solo un vehiculo.

ej
`<warpit><Plate>XT8498</Plate><Year>2004</Year><Motor>Z6227166</Motor><Maker>MAZDA</Maker><Model>3 1 6</Model><Sts>100</Sts><Cache>2016-02-09 16:15:03</Cache><item><Social>JdjZZZ42HT</Social><Service><item><Id>468755</Id><Plate>XT8498</Plate><Revision>2014-12-30</Revision><Due>2015-11-19</Due><Status>A&#xD;</Status></item></Service></item></warpit>`

`<warpit><item><Plate>BLBD26</Plate><Class>AUTOMOVIL</Class><Color>GRIS</Color><Maker>TOYOTA</Maker><Model>YARIS XLI 1.5</Model><Year>2008</Year><Chasis>JTDBT933684023314</Chasis><Motor>1NZC947680</Motor><Sts>100</Sts><Cache>2015-03-28 18:24:08</Cache><Reporter>0</Reporter><Blocked>0</Blocked><Social>q2snwabGiB</Social><Service><item><Id>134833</Id><Plate>BLBD26</Plate><Revision>2014-10-30</Revision><Due>2015-09-30</Due><Status>A&#xD;</Status></item></Service></item></warpit>`

`<warpit><Plate>HBGT14</Plate><Year/><Motor/><Maker/><Model/><Sts>40</Sts><Cache>2016-02-09 15:56:30</Cache><item><Social>2vqt9Cyrfl</Social><Service/></item></warpit>`

**Comment by oscarvalenzuelab** [comment]
Excelente aporte!
Creo que el problema radica en si la respuesta se encuentra en el caché o no. Si es una nueva consulta, responderá no itemizado, si los datos están en el cache de las ultimas 48hrs entonces responde itemizado.
Corregiremos este problema lo antes posible y notificaremos vía email.

**Comment by apenailillo** [comment]
Excelente, Gracias oscar

**Comment by oscarvalenzuelab** [comment]
Al parecer la diferencia en la estructura fue corregido. Nota que los elementos vacíos son debido a que no contamos con esos datos.
