### ISSUE TITLE
api getplateinfo wont working

### ISSUE THREAD

**Issue by gnavarroco** [oscarvalenzuelab/multidata-api-clients#5]
Hola, la api de ustedes no está funcionando

"{
  "error": "no response from server"
}
"

**Comment by oscarvalenzuelab** [comment]
Hola!, es posible que haya sido el dia en que tuvimos sobrecarga en nuestros servidores debido a que uno de los desarrolladores estaba consultando masivamente. Ese desarrollador fue dado de baja y se mejoraron los servicios para evitar que suceda nuevamente. Intentalo ahora, y nos cuentas si tienes problemas. Salu2!

**Comment by gnavarroco** [comment]
Hola Oscar,

Continua igual :(

**Comment by oscarvalenzuelab** [comment]
Puedes comentarme que codigo estás usando? yo lo acabo de probar con mi cuenta personal y un cliente en PHP y mira:
root@ip-10-0-0-50:~# php multidata.php 
[{"Plate":"CFZP61","Class":"AUTOMOVIL","Color":"AZUL","Maker":"CHEVROLET","Model":"AVEO SEDAN LS NB 1.4","Year":"2010","Chasis":"KL1TD53739B694912","Motor":"F14D37495211","Sts":"100","Cache":"2015-03-28 18:24:08","Reporter":"0","Blocked":"0","Service":[{"Plate":"CFZP61","Revision":"2014-04-12","Due":"2015-04-30","Status":"A"}],"Social":"6Z4CVy4VEI"}]1

Por favor, asegurate que estas usando el ejemplo correcto, yo estoy usando este:
https://github.com/oscarvalenzuelab/multidata-api-clients/blob/master/multidata.php

Fijate tambien que tu APIKey sea valida. La q aparece en el código es solo de ejemplo.

**Comment by oscarvalenzuelab** [comment]
Otro ejemplo es que la KEY (810f71c9) que usa comparaonline generada por @apenailillo consulto el 7/25  370 requests exitosos y ayer 124.

**Comment by oscarvalenzuelab** [comment]
Otro factor q puede ser, es q hayas generado mas conexiones de las permitidas y el sistema te haya bloqueado. Cuantas consultas has intentado hacer? Recuerda que hay un limite por dia.

**Comment by oscarvalenzuelab** [comment]
Mmm. me da la impresion de que eso puede ser, dado que ustedes pasaron de usar entre 80-100 consultas a 300-370. Cuando el limite es 300. Ojo con eso.

**Comment by gnavarroco** [comment]
La verdad es que no tengo idea de cuantos fueron, ¿cuando bloquea por cuanto tiempo queda bloqueado?
Pregunto eso porque hace 2 semanas que no logramos hacer ninguna consulta :(

**Comment by oscarvalenzuelab** [comment]
Mmmm, eso es muy muy raro, normalmente el bloqueo es de 2 a 24hrs dependiendo del número de consultas. Insisto el Key de Andres tiene 300 consultas exitosas por dia. Cual es el ID (email) de desarrollador que estas usando? verificaste al ingresar al panel el número de consultas que tienes por dia?
Yo probe 2 clientes (java y PHP) y ambos están funcionando. Incluso nuestro Bot en FB que usa la misma API está funcionando.

Baja el codigo PHP y ejecutalo en una maquina personal o algo asi, que tenga salida directa a internet.

**Comment by apenailillo** [comment]
@gnavarroco voy a traspasarte el acceso al dashboard del api de multidata, donde salen los números que dice @oscarvalenzuelab (ayer hubieron 204).

Saludos

**Comment by gnavarroco** [comment]
@oscarvalenzuelab Gracias Oscar! algo estaba explotando aquí mismo :( ahora esta arreglado!
@apenailillo Gracias Pepe por la info!!

Saludos!
\\Guilherme
