### ISSUE TITLE
Error consulta rut persona

### ISSUE THREAD

**Issue by ddiagar** [oscarvalenzuelab/multidata-api-clients#8]
Estimado,

Al intentar hacer funcionar mi key (56a68fe7c962eb000100012ac610c660792f4f4a616114c52ab97648) y consultar el rut de una persona, siempre me da el mismo mensaje 

![image](https://cloud.githubusercontent.com/assets/12042533/22036708/2cdc5874-dcd3-11e6-9f93-0f59e5b73aa2.png)

A que se debe?, esta funcionando correctamente la API?

Quedo atento a sus comentarios.

Gracias.

Saludos,

Danilo Díaz G.

**Comment by oscarvalenzuelab** [comment]
Danilo, el problema ocurre tambien al ejecutar el script? o solo en la interfaz de documentacion?

Encontramos algunos problemas con la interfaz de documentacion, por lo que estamos migrando a otro proveedor. Por favor intenta consultando la api con uno de los scripts de ejemplo y me cuentas.

Salu2

**Comment by oscarvalenzuelab** [comment]
Ping?!

**Comment by oscarvalenzuelab** [comment]
Cerrando al no haber recibido respuesta.
