### ISSUE TITLE
Error en el portal de desarrolladores

### ISSUE THREAD

**Issue by huolivares** [oscarvalenzuelab/multidata-api-clients#9]
Estimad@s,

   Les comento que en el portal de desarrolladores no puede hacer nada ni siquiera registrarme, me muestra lo siguiente al intentar realizar cualquier acción (VER RECURSOS, REGISTRARSE):

![image](https://cloud.githubusercontent.com/assets/18075941/24703401/776e95f8-19d9-11e7-8c71-f7168d4cd802.png)

**Comment by oscarvalenzuelab** [comment]
Hola,

Dado que nos encontramos trabajando en la siguiente version, la cual no usara el mismo software, hemos cerrado el accesso/registro. Si tienes una urgencia donde necesitas usar/probar el servicio, escribeme un correo a ovalenzuela_AT_multidata.cl y te ayudo a crear una cuenta. Pero recuerda, este servicio sera migrado pronto, y los formatos de consulta/api seran similares, pero no iguales.

Saludos,
Oscar.
